---
apiVersion: v1
kind: Service
metadata:
  name: frontend-node
  namespace: frontend
  labels:
    app: frontend-node
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 3000
  selector:
    app: frontend-node
  type: LoadBalancer  




